### ISSUE TITLE
Embed index.html in binary

### ISSUE THREAD

**Issue by roelrymenants** [roelrymenants/liddly#1]
It would be nice to have the index.html embedded into the binary (and adding the option to use an on-disk version instead).

Possible licensing issue?

**Comment by ay-wowed** [comment]
TiddlyWiki is under a BSD 3-Clause License; embedding in the binary is OK as long as you mention its terms in the documentation.

**Comment by roelrymenants** [comment]
[statik](https://github.com/rakyll/statik) seems like a nice enough solution and has good references
